# Generated by Django 3.2.7 on 2021-09-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='text',
            new_name='mensagem',
        ),
    ]
