# Generated by Django 3.2.7 on 2021-09-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0002_auto_20210909_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre',
            name='img',
            field=models.ImageField(blank='True', default='usuario.png', null='True', upload_to='sobre_nos'),
        ),
    ]
