# Generated by Django 3.2.7 on 2021-09-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0003_servico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='nomeservico',
            new_name='nome_servico',
        ),
    ]
