# Generated by Django 3.2.7 on 2021-09-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0003_alter_sobre_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank='True', max_length=11, null='True'),
        ),
    ]
