# Generated by Django 3.2.7 on 2021-09-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0004_alter_contato_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre',
            name='img',
            field=models.ImageField(blank='True', null='True', upload_to='sobre_nos'),
        ),
    ]
